version: '3.8'
services:
  harvester:
    build: .
    volumes:
      - .:/app
    env_file:
      - config.env
    ports:
        - "${NESTER_LISTEN_PORT}:${NESTER_LISTEN_PORT}"
        - "${FLASK_LISTEN_PORT}:${FLASK_LISTEN_PORT}"
