version: '3.8'
services:
  harvester:
    build:
        context: .
        dockerfile: Dockerfile
        args:
            - NESTER_LISTEN_PORT=${NESTER_LISTEN_PORT}
            - FLASK_LISTEN_PORT=${FLASK_LISTEN_PORT}
    volumes:
      - .:/app
    env_file:
      - config.env
    ports:
        - "${NESTER_LISTEN_PORT}:${NESTER_LISTEN_PORT}"
        - "${FLASK_LISTEN_PORT}:${FLASK_LISTEN_PORT}"
